### ISSUE TITLE
Develop ID verification workflow

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflverse-players#2]
This should be used to verify ID corrections explained in #1

**Comment by tanho63** [comment]
should: 
- internally check duplicates
- ensure id is valid within source? (i.e. go visit PFR page, go visit PFF page, check name within rosters for gsis etc?)
- compare name similarity to be within threshold?

**Comment by mrcaseb** [comment]
> ensure id is valid within source? (i.e. go visit PFR page, go visit PFF page, check name within rosters for gsis etc?)

Imo this is partly the responsibility of the PR creator. I want at least links to the relevant pages that help human checks

**Comment by mrcaseb** [comment]
Branch protection and data sanity through tests implemented. 

Contribution guide added
